title = "My cool new Blog"
baseURL = "https://example.com"
theme = "bilberry-hugo-theme"

enableRobotsTXT = true

# Change to your content language. Supported values: en, de, es, fr, ru
DefaultContentLanguage = "en"

# Enable / Disable Google Analytics statistics for your site
googleAnalytics = ""

# Enable / Disable comments on the articles via Disqus.
disqusShortname = "bilberry-hugo-theme"

[params]
  # Favicon for the browser's favorites and tabs
  favicon = "" # set a favicon icon

  # Custom CSS / JS modules that will be imported by the template.
  # Files are relative to the static/ directory or a URL.
  # Files are imported in the order they appear here, after
  # theme.css and theme.js, respectively.
  css_modules = []
  js_modules = []

  # Description and meta data for the search engines
  author = "Lednerb"
  description = "Bilberry Premium Theme for Hugo."
  keywords = "blog,personal,responsive,search,font awesome,pages,posts,multilingual,highlight.js,syntax highlighting,premium,shortcuts"

  # How many articles should be displayed at once?
  paginate = 7

  # Enable / Disable MathJax
  enable_mathjax    = false

  # Enable / Disable algolia search
  algolia_search    = true
  algolia_appId     = "Y2C4RWMPXW"
  algolia_apiKey    = "50ea7f8c41c0ad233926e0be2b769ed1"
  algolia_indexName = "default-content"

  # Header configuration
    # your subtitle if you want to use any
    subtitle = "Hello World! This is the most epic subtitle ever."

    # if you want to use gravatar for the header image
    gravatarEMail = ""

    # set an path to the image file you want to use | overwrites gravatar
    customImage = ""

    # always display the top navigation (with pages and search) on non-mobile screens
    permanentTopNav = false

  # social media profile urls for the footer links
  facebook   = ""
  twitter    = "https://twitter.com/TheRealLednerb"
  googleplus = ""
  pinterest  = ""
  instagram  = ""
  tumblr     = ""
  youtube    = ""
  vimeo      = ""
  github     = "https://github.com/Lednerb"

# don't change anything here
[taxonomies]
  author   = "author"
  tag      = "tags"
  category = "categories"

[outputs]
  home = [ "HTML", "JSON" ]
  page = [ "HTML" ]
